package openrr.map.soil;

public enum SoilType {
DIRT, SOIL, LOOSE_ROCK, HARD_ROCK, SOLID_ROCK,
CHRYSTAL_SEAM, ORE_SEAM, RECHARGE_SEAM,
LAVA, WATER,
LAVA_EROSION_STEP1, LAVA_EROSION_STEP2, LAVA_EROSION_STEP3, LAVA_EROSION_STEP4,
POWER_PATH_SQUARE, POWER_PATH_CROSS, POWER_PATH_STRAIGHT, POWER_PATH_CORNER, POWER_PATH_TINTERSECTION, POWER_PATH_END,
RUBBLE_STEP1, RUBBLE_STEP2, RUBBLE_STEP3, RUBBLE_STEP4,
SLUG_HOLE
}
