package openrr.test;

public enum EventType {
	MOUSE_MOVE,
	MOUSE_PRESS,
	MOUSE_RELEASE,
	TIMER_TICK,
	TIMER_EXPIRED,
	NEW_DELAY_HOVER_TIMER,
	BUTTON_RELEASE,
	GUIELEMENT_MOVING,
	GUIELEMENT_MOVED
}
