package orre.rendering;

public enum ShaderProperty {
	TEXTURE, MATERIAL_SHININESS, MATERIAL_AMBIENT, MATERIAL_DIFFUSE, MATERIAL_SPECULAR, MATERIAL_EMISSION, LIGHT_POSITION, LIGHT_DIFFUSE, LIGHT_SPECULAR, LIGHT_AMBIENT
	
}
